### ISSUE TITLE
after this setup qemu-kvm is still missing

### ISSUE THREAD

**Issue by do3cc** [debops/ansible-kvm#5]

**Comment by drybjed** [comment]
Could be, we re in a weird period when `qemu-kvm` is used to setup KVM on Wheezy, and on Ubuntu and Jessie `qemu-system-*` packages are used instead. This role probably needs to be extended to handle different package lists on different distributions.

**Comment by drybjed** [comment]
Fixed by https://github.com/debops/ansible-kvm/commit/b0b9bce8181c4d3ad35d4b18ba848e4f8878c6e9
